export interface MenuItem {
    timeOfDay?: string;
    time?: string;
    productName?: string;
    productWeight?: string;
    productAmount?: string;
}

export const menuLists: { [program: string]: { [day: string]: MenuItem[] } } = {
    'Express Fit': {
        ПН: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Фриттата с сыром и кабачками',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Фермерский йогурт, - Полезное печенье из сухофруктов и орехов',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Люля-кебаб из индейки, - Летний салат с маслинами и сыром',
                productWeight: '100гр, 100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Творожное суфле с какао и вишней',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Рыбный терен, - Овощи гриль',
                productWeight: '100 гр, 150гр',
            },
        ],
        ВТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Мини сырники',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Похлебка грибная, - печенье',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Биточки из сыра и курицы с запеченным картофелем',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Ежики мясные с отварной гречкой',
                productWeight: '100гр',
            },
        ],
        СР: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блин-омлет с куринным филе',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Борщ с говядиной',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета домашняя с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из летних овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Биточек куринный с капустой и картофельным пюре',
                productWeight: '100гр',
            },
        ],
        ЧТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сырники творжные с яблочной начинкой',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп по-деревенский с курицей',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Лапшка гречневая с цукини и ореховым соусом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат Мимоза',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Сосиски куриные с картофельным пюре',
                productWeight: '100гр',
            },
        ],
        ПТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Каша рисовая молочная',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Кремы-суп из тыквы',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Шницель куриный в сырной панировке с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Баклажан по-сычуаньски',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Голубцы ленивые в сметанном соусе',
                productWeight: '100гр',
            },
        ],
        СБ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блинчики с творогом',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из моркови с сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Пельмени отварные с курицей',
                productWeight: '100гр',
            },
        ],
        ВС: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сендвич Жульен с курицей',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Грузинский суп из фасоли с овощами',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Кабачки фаршированные мясом и рисом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат с курицей и ананасами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Гречка по-купечески',
                productWeight: '100гр',
            },
        ],
    },

    slim: {
        ПН: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Мини сырники',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Похлебка грибная',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Биточки из сыра и курицы с запеченным картофелем',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Ежики мясные с отварной гречкой',
                productWeight: '100гр',
            },
        ],
        ВТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блин-омлет с куринным филе',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Борщ с говядиной',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета домашняя с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из летних овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Биточек куринный с капустой и картофельным пюре',
                productWeight: '100гр',
            },
        ],
        СР: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сырники творжные с яблочной начинкой',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп по-деревенский с курицей',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Лапшка гречневая с цукини и ореховым соусом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат Мимоза',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Сосиски куриные с картофельным пюре',
                productWeight: '100гр',
            },
        ],
        ЧТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Каша рисовая молочная',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Кремы-суп из тыквы',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Шницель куриный в сырной панировке с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Баклажан по-сычуаньски',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Голубцы ленивые в сметанном соусе',
                productWeight: '100гр',
            },
        ],
        ПТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блинчики с творогом',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета куриная с картофельным пюре и овощами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из моркови с сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Пельмени отварные с курицей',
                productWeight: '100гр',
            },
        ],
        СБ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сендвич Жульен с курицей',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Грузинский суп из фасоли с овощами',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Кабачки фаршированные мясом и рисом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат с курицей и ананасами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Гречка по-купечески',
                productWeight: '100гр',
            },
        ],
        ВС: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Фриттата с сыром и кабачками',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Фермерский йогурт, - Полезное печенье из сухофруктов и орехов',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Люля-кебаб из индейки, - Летний салат с маслинами и сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Творожное суфле с какао и вишей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Рыбный терен, Овощи гриль',
                productWeight: '100гр',
            },
        ],
    },
    fitness: {
        ПН: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блин-омлет с куринным филе',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Борщ с говядиной',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета домашняя с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из летних овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Биточек куринный с капустой и картофельным пюре',
                productWeight: '100гр',
            },
        ],

        ВТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сырники творжные с яблочной начинкой',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп по-деревенский с курицей',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Лапшка гречневая с цукини и ореховым соусом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат Мимоза',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Сосиски куриные с картофельным пюре',
                productWeight: '100гр',
            },
        ],
        СР: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Каша рисовая молочная',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Кремы-суп из тыквы',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Шницель куриный в сырной панировке с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Баклажан по-сычуаньски',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Голубцы ленивые в сметанном соусе',
                productWeight: '100гр',
            },
        ],
        ЧТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блинчики с творогом',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета куриная с картофельным пюре и овощами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из моркови с сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Пельмени отварные с курицей',
                productWeight: '100гр',
            },
        ],
        ПТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сендвич Жульен с курицей',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Грузинский суп из фасоли с овощами',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Кабачки фаршированные мясом и рисом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат с курицей и ананасами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Гречка по-купечески',
                productWeight: '100гр',
            },
        ],
        СБ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Фриттата с сыром и кабачками',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Фермерский йогурт, - Полезное печенье из сухофруктов и орехов',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Люля-кебаб из индейки, - Летний салат с маслинами и сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Творожное суфле с какао и вишей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Рыбный терен, Овощи гриль',
                productWeight: '100гр',
            },
        ],
        ВС: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Мини сырники',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Похлебка грибная',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Биточки из сыра и курицы с запеченным картофелем',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Ежики мясные с отварной гречкой',
                productWeight: '100гр',
            },
        ],
    },

    balance: {
        ПН: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сырники творжные с яблочной начинкой',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп по-деревенский с курицей',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Лапшка гречневая с цукини и ореховым соусом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат Мимоза',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Сосиски куриные с картофельным пюре',
                productWeight: '100гр',
            },
        ],
        ВТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Каша рисовая молочная',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Кремы-суп из тыквы',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Шницель куриный в сырной панировке с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Баклажан по-сычуаньски',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Голубцы ленивые в сметанном соусе',
                productWeight: '100гр',
            },
        ],
        СР: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блинчики с творогом',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета куриная с картофельным пюре и овощами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из моркови с сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Пельмени отварные с курицей',
                productWeight: '100гр',
            },
        ],
        ЧТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сендвич Жульен с курицей',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Грузинский суп из фасоли с овощами',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Кабачки фаршированные мясом и рисом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат с курицей и ананасами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Гречка по-купечески',
                productWeight: '100гр',
            },
        ],
        ПТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Фриттата с сыром и кабачками',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Фермерский йогурт, - Полезное печенье из сухофруктов и орехов',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Люля-кебаб из индейки, - Летний салат с маслинами и сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Творожное суфле с какао и вишей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Рыбный терен, Овощи гриль',
                productWeight: '100гр',
            },
        ],
        СБ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Мини сырники',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Похлебка грибная',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Биточки из сыра и курицы с запеченным картофелем',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Ежики мясные с отварной гречкой',
                productWeight: '100гр',
            },
        ],
        ВС: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блин-омлет с куринным филе',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Борщ с говядиной',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета домашняя с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из летних овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Биточек куринный с капустой и картофельным пюре',
                productWeight: '100гр',
            },
        ],
    },

    'balance +': {
        ПН: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Каша рисовая молочная',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Кремы-суп из тыквы',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Шницель куриный в сырной панировке с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Баклажан по-сычуаньски',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Голубцы ленивые в сметанном соусе',
                productWeight: '100гр',
            },
        ],
        ВТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блинчики с творогом',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета куриная с картофельным пюре и овощами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из моркови с сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Пельмени отварные с курицей',
                productWeight: '100гр',
            },
        ],
        СР: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сендвич Жульен с курицей',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Грузинский суп из фасоли с овощами',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Кабачки фаршированные мясом и рисом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат с курицей и ананасами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Гречка по-купечески',
                productWeight: '100гр',
            },
        ],
        ЧТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Фриттата с сыром и кабачками',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Фермерский йогурт, - Полезное печенье из сухофруктов и орехов',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Люля-кебаб из индейки, - Летний салат с маслинами и сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Творожное суфле с какао и вишей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Рыбный терен, Овощи гриль',
                productWeight: '100гр',
            },
        ],
        ПТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Мини сырники',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Похлебка грибная',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Биточки из сыра и курицы с запеченным картофелем',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Ежики мясные с отварной гречкой',
                productWeight: '100гр',
            },
        ],
        СБ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блин-омлет с куринным филе',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Борщ с говядиной',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета домашняя с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из летних овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Биточек куринный с капустой и картофельным пюре',
                productWeight: '100гр',
            },
        ],
        ВС: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сырники творжные с яблочной начинкой',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп по-деревенский с курицей',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Лапшка гречневая с цукини и ореховым соусом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат Мимоза',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Сосиски куриные с картофельным пюре',
                productWeight: '100гр',
            },
        ],
    },

    strong: {
        ПН: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блинчики с творогом',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета куриная с картофельным пюре и овощами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из моркови с сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Пельмени отварные с курицей',
                productWeight: '100гр',
            },
        ],
        ВТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сендвич Жульен с курицей',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Грузинский суп из фасоли с овощами',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Кабачки фаршированные мясом и рисом',
                productWeight: '100 гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат с курицей и ананасами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Гречка по-купечески',
                productWeight: '100гр',
            },
        ],
        СР: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Фриттата с сыром и кабачками',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Фермерский йогурт, - Полезное печенье из сухофруктов и орехов',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Люля-кебаб из индейки, - Летний салат с маслинами и сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Творожное суфле с какао и вишей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Рыбный терен, - Овощи гриль',
                productWeight: '100гр',
            },
        ],
        ЧТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Мини сырники',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Похлебка грибная',
                productWeight: '150гп',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Биточки из сыра и курицы с запеченным картофелем',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Ежики мясные с отварной гречкой',
                productWeight: '100гр',
            },
        ],
        ПТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блин-омлет с куринным филе',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Борщ с говядиной',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета домашняя с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из летних овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Биточек куринный с капустой и картофельным пюре',
                productWeight: '100гр',
            },
        ],
        СБ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сырники творжные с яблочной начинкой',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп по-деревенский с курицей',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Лапшка гречневая с цукини и ореховым соусом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат Мимоза',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Сосиски куриные с картофельным пюре',
                productWeight: '100гр',
            },
        ],
        ВС: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Каша рисовая молочная',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Кремы-суп из тыквы',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Шницель куриный в сырной панировке с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Баклажан по-сычуаньски',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Голубцы ленивые в сметанном соусе',
                productWeight: '100гр',
            },
        ],
    },

    'maxi fit': {
        ПН: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Каша рисовая молочная',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Кремы-суп из тыквы',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Шницель куриный в сырной панировке с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Баклажан по-сычуаньски',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Голубцы ленивые в сметанном соусе',
                productWeight: '100гр',
            },
        ],
        ВТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блинчики с творогом',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп-грибной с домашней лапшой',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета куриная с картофельным пюре и овощами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из моркови с сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Пельмени отварные с курицей',
                productWeight: '100гр',
            },
        ],
        СР: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сендвич Жульен с курицей',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Грузинский суп из фасоли с овощами',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Кабачки фаршированные мясом и рисом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат с курицей и ананасами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Гречка по-купечески',
                productWeight: '100гр',
            },
        ],
        ЧТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Фриттата с сыром и кабачками',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Фермерский йогурт, - Полезное печенье из сухофруктов и орехов',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Люля-кебаб из индейки, - Летний салат с маслинами и сыром',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Творожное суфле с какао и вишей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Рыбный терен, Овощи гриль',
                productWeight: '100гр',
            },
        ],
        ПТ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Мини сырники',
                productWeight: '200 гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Похлебка грибная',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Биточки из сыра и курицы с запеченным картофелем',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Ежики мясные с отварной гречкой',
                productWeight: '100гр',
            },
        ],
        СБ: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Блин-омлет с куринным филе',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Борщ с говядиной',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Котлета домашняя с макаронами',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат из летних овощей',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Биточек куринный с капустой и картофельным пюре',
                productWeight: '100гр',
            },
        ],
        ВС: [
            {
                timeOfDay: 'Завтрак',
                time: '7:00 - 9:00',
                productName: '- Сырники творжные с яблочной начинкой',
                productWeight: '200гр',
            },
            {
                timeOfDay: '2-й завтрак',
                time: '10:00 - 12:00',
                productName: '- Суп по-деревенский с курицей',
                productWeight: '150гр',
                productAmount: '2 шт',
            },
            {
                timeOfDay: 'Обед',
                time: '13:00 - 15:00',
                productName: '- Лапшка гречневая с цукини и ореховым соусом',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Полдник',
                time: '16:00 - 17:30',
                productName: '- Салат Мимоза',
                productWeight: '100гр',
            },
            {
                timeOfDay: 'Ужин',
                time: '19:00 - 20:00',
                productName: '- Сосиски куриные с картофельным пюре',
                productWeight: '100гр',
            },
        ],
    },
};
